/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { createThemeContract } from '@vanilla-extract/css';

export const themeVars = createThemeContract({});
