/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { RecursicaRecursicaTokens } from './RecursicaRecursicaTokens';
import { themeVars } from './RecursicaRecursicaContractTheme.css';
import { uiKit } from './RecursicaRecursicaUiKit';

export const recursica = {
  ...uiKit,
  ...themeVars,
  ...RecursicaRecursicaTokens,
};
