/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/
export { DefaultLightTheme } from './RecursicaRecursicaDefaultLightTheme.css';
import { DefaultLightTheme } from './RecursicaRecursicaDefaultLightTheme.css';
export { DefaultDarkTheme } from './RecursicaRecursicaDefaultDarkTheme.css';
import { DefaultDarkTheme } from './RecursicaRecursicaDefaultDarkTheme.css';

export const Themes = {
  'Default': {
    'Light': DefaultLightTheme,
		'Dark': DefaultDarkTheme
  }
}