/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { colorsTuple, createTheme } from '@mantine/core'
import { themeVars } from './RecursicaRecursicaContractTheme.css'

export const mantineTheme = createTheme({
  primaryColor: 'color-1-scale-default',
  white: themeVars['color/background/default'],
  breakpoints: {
    
  },
  colors: {
    
  },
  radius: {
    
  },
  fontSizes: {
    
  }
})