/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { colorsTuple, createTheme } from '@mantine/core'
import { themeVars } from './RecursicaRecursicaContractTheme.css'

export const mantineTheme = createTheme({
  primaryColor: 'color-1-scale-default',
  white: themeVars['color/background/default'],
  breakpoints: {
    
  },
  colors: {
    
  },
  radius: {
    "size-border-radius-0-5x": "4px",
		"size-border-radius-4x": "32px",
		"size-border-radius-1-5x": "12px",
		"size-border-radius-3x": "24px",
		"size-border-radius-default": "8px",
		"size-border-radius-2x": "16px"
  },
  fontSizes: {
    "font-size-5xl": "36px",
		"font-size-4xl": "32px",
		"font-size-md": "16px",
		"font-size-6xl": "40px",
		"font-size-3xl": "28px",
		"font-size-2xs": "10px",
		"font-size-2xl": "24px",
		"font-size-xl": "20px",
		"font-size-xs": "12px",
		"font-size-lg": "18px",
		"font-size-sm": "14px"
  }
})