/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { colorsTuple, createTheme } from '@mantine/core'
import { themeVars } from './RecursicaRecursicaContractTheme.css';

export const mantineTheme = createTheme({
  primaryColor: 'color-1-scale-default',
  white: themeVars['color/background/default'],
  breakpoints: {},
  colors: {
    'color-actionable-default': colorsTuple(themeVars['color/actionable/default']),
    'color-actionable-hover': colorsTuple(themeVars['color/actionable/hover']),
    'color-actionable-pressed': colorsTuple(themeVars['color/actionable/pressed']),
    'color-actionable-focused': colorsTuple(themeVars['color/actionable/focused']),
    'color-actionable-selected': colorsTuple(themeVars['color/actionable/selected']),
    'color-actionable-disabled': colorsTuple(themeVars['color/actionable/disabled']),
    'color-alert-default': colorsTuple(themeVars['color/alert/default']),
    'color-alert-900': colorsTuple(themeVars['color/alert/900']),
    'color-alert-800': colorsTuple(themeVars['color/alert/800']),
    'color-alert-700': colorsTuple(themeVars['color/alert/700']),
    'color-alert-600': colorsTuple(themeVars['color/alert/600']),
    'color-alert-500': colorsTuple(themeVars['color/alert/500']),
    'color-alert-400': colorsTuple(themeVars['color/alert/400']),
    'color-alert-300': colorsTuple(themeVars['color/alert/300']),
    'color-alert-200': colorsTuple(themeVars['color/alert/200']),
    'color-alert-100': colorsTuple(themeVars['color/alert/100']),
    'color-alert-50': colorsTuple(themeVars['color/alert/50']),
    'color-alert-states-hover': colorsTuple(themeVars['color/alert/states/hover']),
    'color-alert-states-pressed': colorsTuple(themeVars['color/alert/states/pressed']),
    'color-alert-states-focused': colorsTuple(themeVars['color/alert/states/focused']),
    'color-alert-states-selected': colorsTuple(themeVars['color/alert/states/selected']),
    'color-alert-states-disabled': colorsTuple(themeVars['color/alert/states/disabled']),
    'color-1-scale-states-hover': colorsTuple(themeVars['color/1-scale/states/hover']),
    'color-1-scale-states-pressed': colorsTuple(themeVars['color/1-scale/states/pressed']),
    'color-1-scale-states-focused': colorsTuple(themeVars['color/1-scale/states/focused']),
    'color-1-scale-states-selected': colorsTuple(themeVars['color/1-scale/states/selected']),
    'color-1-scale-states-disabled': colorsTuple(themeVars['color/1-scale/states/disabled']),
    'color-background-default': colorsTuple(themeVars['color/background/default']),
    'color-background-hover': colorsTuple(themeVars['color/background/hover']),
    'color-background-pressed': colorsTuple(themeVars['color/background/pressed']),
    'color-background-focused': colorsTuple(themeVars['color/background/focused']),
    'color-background-selected': colorsTuple(themeVars['color/background/selected']),
    'color-surface-default': colorsTuple(themeVars['color/surface/default']),
    'color-surface-hover': colorsTuple(themeVars['color/surface/hover']),
    'color-surface-pressed': colorsTuple(themeVars['color/surface/pressed']),
    'color-surface-focused': colorsTuple(themeVars['color/surface/focused']),
    'color-surface-selected': colorsTuple(themeVars['color/surface/selected']),
    'color-surface-disabled': colorsTuple(themeVars['color/surface/disabled']),
    'color-neutral-900': colorsTuple(themeVars['color/neutral/900']),
    'color-neutral-800': colorsTuple(themeVars['color/neutral/800']),
    'color-neutral-700': colorsTuple(themeVars['color/neutral/700']),
    'color-neutral-600': colorsTuple(themeVars['color/neutral/600']),
    'color-neutral-500': colorsTuple(themeVars['color/neutral/500']),
    'color-neutral-400': colorsTuple(themeVars['color/neutral/400']),
    'color-neutral-300': colorsTuple(themeVars['color/neutral/300']),
    'color-neutral-200': colorsTuple(themeVars['color/neutral/200']),
    'color-neutral-100': colorsTuple(themeVars['color/neutral/100']),
    'color-neutral-50': colorsTuple(themeVars['color/neutral/50']),
    'color-1-scale-default': colorsTuple(themeVars['color/1-scale/default']),
    'color-background-disabled': colorsTuple(themeVars['color/background/disabled']),
    'color-2-scale-default': colorsTuple(themeVars['color/2-scale/default']),
    'color-3-scale-900': colorsTuple(themeVars['color/3-scale/900']),
    'color-4-scale-900': colorsTuple(themeVars['color/4-scale/900']),
    'color-4-scale-800': colorsTuple(themeVars['color/4-scale/800']),
    'color-4-scale-700': colorsTuple(themeVars['color/4-scale/700']),
    'color-4-scale-600': colorsTuple(themeVars['color/4-scale/600']),
    'color-4-scale-500': colorsTuple(themeVars['color/4-scale/500']),
    'color-4-scale-400': colorsTuple(themeVars['color/4-scale/400']),
    'color-4-scale-300': colorsTuple(themeVars['color/4-scale/300']),
    'color-4-scale-200': colorsTuple(themeVars['color/4-scale/200']),
    'color-4-scale-100': colorsTuple(themeVars['color/4-scale/100']),
    'color-4-scale-50': colorsTuple(themeVars['color/4-scale/50']),
    'color-3-scale-800': colorsTuple(themeVars['color/3-scale/800']),
    'color-3-scale-700': colorsTuple(themeVars['color/3-scale/700']),
    'color-3-scale-600': colorsTuple(themeVars['color/3-scale/600']),
    'color-3-scale-500': colorsTuple(themeVars['color/3-scale/500']),
    'color-3-scale-400': colorsTuple(themeVars['color/3-scale/400']),
    'color-3-scale-300': colorsTuple(themeVars['color/3-scale/300']),
    'color-3-scale-200': colorsTuple(themeVars['color/3-scale/200']),
    'color-3-scale-100': colorsTuple(themeVars['color/3-scale/100']),
    'color-3-scale-50': colorsTuple(themeVars['color/3-scale/50']),
    'color-stroke-default': colorsTuple(themeVars['color/stroke/default']),
    'color-stroke-hover': colorsTuple(themeVars['color/stroke/hover']),
    'color-stroke-focused': colorsTuple(themeVars['color/stroke/focused']),
    'color-stroke-pressed': colorsTuple(themeVars['color/stroke/pressed']),
    'color-stroke-selected': colorsTuple(themeVars['color/stroke/selected']),
    'color-stroke-disabled': colorsTuple(themeVars['color/stroke/disabled']),
    'color-stroke-error': colorsTuple(themeVars['color/stroke/error']),
    'color-success-default': colorsTuple(themeVars['color/success/default']),
    'color-success-900': colorsTuple(themeVars['color/success/900']),
    'color-success-800': colorsTuple(themeVars['color/success/800']),
    'color-success-700': colorsTuple(themeVars['color/success/700']),
    'color-success-600': colorsTuple(themeVars['color/success/600']),
    'color-success-500': colorsTuple(themeVars['color/success/500']),
    'color-success-400': colorsTuple(themeVars['color/success/400']),
    'color-success-300': colorsTuple(themeVars['color/success/300']),
    'color-success-200': colorsTuple(themeVars['color/success/200']),
    'color-success-100': colorsTuple(themeVars['color/success/100']),
    'color-success-50': colorsTuple(themeVars['color/success/50']),
    'color-2-scale-900': colorsTuple(themeVars['color/2-scale/900']),
    'color-2-scale-800': colorsTuple(themeVars['color/2-scale/800']),
    'color-2-scale-700': colorsTuple(themeVars['color/2-scale/700']),
    'color-2-scale-600': colorsTuple(themeVars['color/2-scale/600']),
    'color-2-scale-500': colorsTuple(themeVars['color/2-scale/500']),
    'color-2-scale-400': colorsTuple(themeVars['color/2-scale/400']),
    'color-2-scale-300': colorsTuple(themeVars['color/2-scale/300']),
    'color-2-scale-200': colorsTuple(themeVars['color/2-scale/200']),
    'color-2-scale-100': colorsTuple(themeVars['color/2-scale/100']),
    'color-2-scale-50': colorsTuple(themeVars['color/2-scale/50']),
    'color-1-scale-900': colorsTuple(themeVars['color/1-scale/900']),
    'color-1-scale-800': colorsTuple(themeVars['color/1-scale/800']),
    'color-1-scale-700': colorsTuple(themeVars['color/1-scale/700']),
    'color-1-scale-600': colorsTuple(themeVars['color/1-scale/600']),
    'color-1-scale-500': colorsTuple(themeVars['color/1-scale/500']),
    'color-1-scale-400': colorsTuple(themeVars['color/1-scale/400']),
    'color-1-scale-300': colorsTuple(themeVars['color/1-scale/300']),
    'color-1-scale-200': colorsTuple(themeVars['color/1-scale/200']),
    'color-1-scale-100': colorsTuple(themeVars['color/1-scale/100']),
    'color-1-scale-50': colorsTuple(themeVars['color/1-scale/50']),
    'color-on-actionable-default': colorsTuple(themeVars['color-on/actionable/default']),
    'color-on-actionable-disabled': colorsTuple(themeVars['color-on/actionable/disabled']),
    'color-on-alert-default-high-emphasis': colorsTuple(
      themeVars['color-on/alert/default/high-emphasis']
    ),
    'color-on-alert-default-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/default/medium-emphasis']
    ),
    'color-on-alert-default-disabled': colorsTuple(themeVars['color-on/alert/default/disabled']),
    'color-on-alert-default-action-text-default': colorsTuple(
      themeVars['color-on/alert/default/action-text-default']
    ),
    'color-on-alert-default-action-text-hover': colorsTuple(
      themeVars['color-on/alert/default/action-text-hover']
    ),
    'color-on-alert-default-action-text-pressed': colorsTuple(
      themeVars['color-on/alert/default/action-text-pressed']
    ),
    'color-on-alert-default-action-text-focused': colorsTuple(
      themeVars['color-on/alert/default/action-text-focused']
    ),
    'color-on-alert-default-action-text-selected': colorsTuple(
      themeVars['color-on/alert/default/action-text-selected']
    ),
    'color-on-alert-default-action-text-disabled': colorsTuple(
      themeVars['color-on/alert/default/action-text-disabled']
    ),
    'color-on-background-high-emphasis': colorsTuple(
      themeVars['color-on/background/high-emphasis']
    ),
    'color-on-background-medium-emphasis': colorsTuple(
      themeVars['color-on/background/medium-emphasis']
    ),
    'color-on-background-disabled': colorsTuple(themeVars['color-on/background/disabled']),
    'color-on-background-alert': colorsTuple(themeVars['color-on/background/alert']),
    'color-on-background-success': colorsTuple(themeVars['color-on/background/success']),
    'color-on-background-action-text-default': colorsTuple(
      themeVars['color-on/background/action-text-default']
    ),
    'color-on-background-action-text-hover': colorsTuple(
      themeVars['color-on/background/action-text-hover']
    ),
    'color-on-background-action-text-pressed': colorsTuple(
      themeVars['color-on/background/action-text-pressed']
    ),
    'color-on-background-action-text-focused': colorsTuple(
      themeVars['color-on/background/action-text-focused']
    ),
    'color-on-background-action-text-selected': colorsTuple(
      themeVars['color-on/background/action-text-selected']
    ),
    'color-on-background-action-text-disabled': colorsTuple(
      themeVars['color-on/background/action-text-disabled']
    ),
    'color-on-1-scale-default-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/default/high-emphasis']
    ),
    'color-on-1-scale-default-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/default/medium-emphasis']
    ),
    'color-on-1-scale-default-disabled': colorsTuple(
      themeVars['color-on/1-scale/default/disabled']
    ),
    'color-on-1-scale-default-action-text-default': colorsTuple(
      themeVars['color-on/1-scale/default/action-text-default']
    ),
    'color-on-1-scale-default-action-text-hover': colorsTuple(
      themeVars['color-on/1-scale/default/action-text-hover']
    ),
    'color-on-1-scale-default-action-text-pressed': colorsTuple(
      themeVars['color-on/1-scale/default/action-text-pressed']
    ),
    'color-on-1-scale-default-action-text-focused': colorsTuple(
      themeVars['color-on/1-scale/default/action-text-focused']
    ),
    'color-on-1-scale-default-action-text-selected': colorsTuple(
      themeVars['color-on/1-scale/default/action-text-selected']
    ),
    'color-on-1-scale-default-action-text-disabled': colorsTuple(
      themeVars['color-on/1-scale/default/action-text-disabled']
    ),
    'color-on-alert-900-high-emphasis': colorsTuple(themeVars['color-on/alert/900/high-emphasis']),
    'color-on-alert-900-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/900/medium-emphasis']
    ),
    'color-on-alert-900-disabled': colorsTuple(themeVars['color-on/alert/900/disabled']),
    'color-on-1-scale-900-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/900/high-emphasis']
    ),
    'color-on-1-scale-900-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/900/medium-emphasis']
    ),
    'color-on-1-scale-900-disabled': colorsTuple(themeVars['color-on/1-scale/900/disabled']),
    'color-on-1-scale-800-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/800/high-emphasis']
    ),
    'color-on-1-scale-800-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/800/medium-emphasis']
    ),
    'color-on-1-scale-800-disabled': colorsTuple(themeVars['color-on/1-scale/800/disabled']),
    'color-on-1-scale-700-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/700/high-emphasis']
    ),
    'color-on-1-scale-700-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/700/medium-emphasis']
    ),
    'color-on-1-scale-700-disabled': colorsTuple(themeVars['color-on/1-scale/700/disabled']),
    'color-on-1-scale-600-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/600/high-emphasis']
    ),
    'color-on-1-scale-600-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/600/medium-emphasis']
    ),
    'color-on-1-scale-600-disabled': colorsTuple(themeVars['color-on/1-scale/600/disabled']),
    'color-on-1-scale-500-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/500/high-emphasis']
    ),
    'color-on-1-scale-500-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/500/medium-emphasis']
    ),
    'color-on-1-scale-500-disabled': colorsTuple(themeVars['color-on/1-scale/500/disabled']),
    'color-on-1-scale-400-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/400/high-emphasis']
    ),
    'color-on-1-scale-400-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/400/medium-emphasis']
    ),
    'color-on-1-scale-400-disabled': colorsTuple(themeVars['color-on/1-scale/400/disabled']),
    'color-on-1-scale-300-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/300/high-emphasis']
    ),
    'color-on-1-scale-300-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/300/medium-emphasis']
    ),
    'color-on-1-scale-300-disabled': colorsTuple(themeVars['color-on/1-scale/300/disabled']),
    'color-on-1-scale-200-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/200/high-emphasis']
    ),
    'color-on-1-scale-200-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/200/medium-emphasis']
    ),
    'color-on-1-scale-200-disabled': colorsTuple(themeVars['color-on/1-scale/200/disabled']),
    'color-on-1-scale-100-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/100/high-emphasis']
    ),
    'color-on-1-scale-100-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/100/medium-emphasis']
    ),
    'color-on-1-scale-100-disabled': colorsTuple(themeVars['color-on/1-scale/100/disabled']),
    'color-on-1-scale-050-high-emphasis': colorsTuple(
      themeVars['color-on/1-scale/050/high-emphasis']
    ),
    'color-on-1-scale-050-medium-emphasis': colorsTuple(
      themeVars['color-on/1-scale/050/medium-emphasis']
    ),
    'color-on-1-scale-050-disabled': colorsTuple(themeVars['color-on/1-scale/050/disabled']),
    'color-on-2-scale-default-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/default/high-emphasis']
    ),
    'color-on-3-scale-900-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/900/high-emphasis']
    ),
    'color-on-4-scale-900-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/900/high-emphasis']
    ),
    'color-on-4-scale-900-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/900/medium-emphasis']
    ),
    'color-on-4-scale-900-disabled': colorsTuple(themeVars['color-on/4-scale/900/disabled']),
    'color-on-4-scale-800-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/800/high-emphasis']
    ),
    'color-on-4-scale-800-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/800/medium-emphasis']
    ),
    'color-on-4-scale-800-disabled': colorsTuple(themeVars['color-on/4-scale/800/disabled']),
    'color-on-4-scale-700-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/700/high-emphasis']
    ),
    'color-on-4-scale-700-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/700/medium-emphasis']
    ),
    'color-on-4-scale-700-disabled': colorsTuple(themeVars['color-on/4-scale/700/disabled']),
    'color-on-4-scale-600-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/600/high-emphasis']
    ),
    'color-on-4-scale-600-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/600/medium-emphasis']
    ),
    'color-on-4-scale-600-disabled': colorsTuple(themeVars['color-on/4-scale/600/disabled']),
    'color-on-4-scale-500-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/500/high-emphasis']
    ),
    'color-on-4-scale-500-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/500/medium-emphasis']
    ),
    'color-on-4-scale-500-disabled': colorsTuple(themeVars['color-on/4-scale/500/disabled']),
    'color-on-4-scale-400-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/400/high-emphasis']
    ),
    'color-on-4-scale-400-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/400/medium-emphasis']
    ),
    'color-on-4-scale-400-disabled': colorsTuple(themeVars['color-on/4-scale/400/disabled']),
    'color-on-4-scale-300-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/300/high-emphasis']
    ),
    'color-on-4-scale-300-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/300/medium-emphasis']
    ),
    'color-on-4-scale-300-disabled': colorsTuple(themeVars['color-on/4-scale/300/disabled']),
    'color-on-4-scale-200-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/200/high-emphasis']
    ),
    'color-on-4-scale-200-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/200/medium-emphasis']
    ),
    'color-on-4-scale-200-disabled': colorsTuple(themeVars['color-on/4-scale/200/disabled']),
    'color-on-4-scale-100-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/100/high-emphasis']
    ),
    'color-on-4-scale-100-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/100/medium-emphasis']
    ),
    'color-on-4-scale-100-disabled': colorsTuple(themeVars['color-on/4-scale/100/disabled']),
    'color-on-4-scale-050-high-emphasis': colorsTuple(
      themeVars['color-on/4-scale/050/high-emphasis']
    ),
    'color-on-4-scale-050-medium-emphasis': colorsTuple(
      themeVars['color-on/4-scale/050/medium-emphasis']
    ),
    'color-on-4-scale-050-disabled': colorsTuple(themeVars['color-on/4-scale/050/disabled']),
    'color-on-3-scale-900-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/900/medium-emphasis']
    ),
    'color-on-3-scale-900-disabled': colorsTuple(themeVars['color-on/3-scale/900/disabled']),
    'color-on-3-scale-800-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/800/high-emphasis']
    ),
    'color-on-3-scale-800-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/800/medium-emphasis']
    ),
    'color-on-3-scale-800-disabled': colorsTuple(themeVars['color-on/3-scale/800/disabled']),
    'color-on-3-scale-700-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/700/high-emphasis']
    ),
    'color-on-3-scale-700-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/700/medium-emphasis']
    ),
    'color-on-3-scale-700-disabled': colorsTuple(themeVars['color-on/3-scale/700/disabled']),
    'color-on-3-scale-600-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/600/high-emphasis']
    ),
    'color-on-3-scale-600-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/600/medium-emphasis']
    ),
    'color-on-3-scale-600-disabled': colorsTuple(themeVars['color-on/3-scale/600/disabled']),
    'color-on-3-scale-500-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/500/high-emphasis']
    ),
    'color-on-3-scale-500-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/500/medium-emphasis']
    ),
    'color-on-3-scale-500-disabled': colorsTuple(themeVars['color-on/3-scale/500/disabled']),
    'color-on-3-scale-400-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/400/high-emphasis']
    ),
    'color-on-3-scale-400-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/400/medium-emphasis']
    ),
    'color-on-3-scale-400-disabled': colorsTuple(themeVars['color-on/3-scale/400/disabled']),
    'color-on-3-scale-300-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/300/high-emphasis']
    ),
    'color-on-3-scale-300-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/300/medium-emphasis']
    ),
    'color-on-3-scale-300-disabled': colorsTuple(themeVars['color-on/3-scale/300/disabled']),
    'color-on-3-scale-200-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/200/high-emphasis']
    ),
    'color-on-3-scale-200-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/200/medium-emphasis']
    ),
    'color-on-3-scale-200-disabled': colorsTuple(themeVars['color-on/3-scale/200/disabled']),
    'color-on-3-scale-100-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/100/high-emphasis']
    ),
    'color-on-3-scale-100-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/100/medium-emphasis']
    ),
    'color-on-3-scale-100-disabled': colorsTuple(themeVars['color-on/3-scale/100/disabled']),
    'color-on-3-scale-050-high-emphasis': colorsTuple(
      themeVars['color-on/3-scale/050/high-emphasis']
    ),
    'color-on-3-scale-050-medium-emphasis': colorsTuple(
      themeVars['color-on/3-scale/050/medium-emphasis']
    ),
    'color-on-3-scale-050-disabled': colorsTuple(themeVars['color-on/3-scale/050/disabled']),
    'color-on-2-scale-default-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/default/medium-emphasis']
    ),
    'color-on-2-scale-default-disabled': colorsTuple(
      themeVars['color-on/2-scale/default/disabled']
    ),
    'color-on-2-scale-900-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/900/high-emphasis']
    ),
    'color-on-2-scale-900-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/900/medium-emphasis']
    ),
    'color-on-2-scale-900-disabled': colorsTuple(themeVars['color-on/2-scale/900/disabled']),
    'color-on-2-scale-800-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/800/high-emphasis']
    ),
    'color-on-2-scale-800-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/800/medium-emphasis']
    ),
    'color-on-2-scale-800-disabled': colorsTuple(themeVars['color-on/2-scale/800/disabled']),
    'color-on-2-scale-700-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/700/high-emphasis']
    ),
    'color-on-2-scale-700-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/700/medium-emphasis']
    ),
    'color-on-2-scale-700-disabled': colorsTuple(themeVars['color-on/2-scale/700/disabled']),
    'color-on-2-scale-600-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/600/high-emphasis']
    ),
    'color-on-2-scale-600-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/600/medium-emphasis']
    ),
    'color-on-2-scale-600-disabled': colorsTuple(themeVars['color-on/2-scale/600/disabled']),
    'color-on-2-scale-500-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/500/high-emphasis']
    ),
    'color-on-2-scale-500-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/500/medium-emphasis']
    ),
    'color-on-2-scale-500-disabled': colorsTuple(themeVars['color-on/2-scale/500/disabled']),
    'color-on-2-scale-400-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/400/high-emphasis']
    ),
    'color-on-2-scale-400-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/400/medium-emphasis']
    ),
    'color-on-2-scale-400-disabled': colorsTuple(themeVars['color-on/2-scale/400/disabled']),
    'color-on-2-scale-300-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/300/high-emphasis']
    ),
    'color-on-2-scale-300-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/300/medium-emphasis']
    ),
    'color-on-2-scale-300-disabled': colorsTuple(themeVars['color-on/2-scale/300/disabled']),
    'color-on-2-scale-200-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/200/high-emphasis']
    ),
    'color-on-2-scale-200-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/200/medium-emphasis']
    ),
    'color-on-2-scale-200-disabled': colorsTuple(themeVars['color-on/2-scale/200/disabled']),
    'color-on-2-scale-100-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/100/high-emphasis']
    ),
    'color-on-2-scale-100-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/100/medium-emphasis']
    ),
    'color-on-2-scale-100-disabled': colorsTuple(themeVars['color-on/2-scale/100/disabled']),
    'color-on-2-scale-050-high-emphasis': colorsTuple(
      themeVars['color-on/2-scale/050/high-emphasis']
    ),
    'color-on-2-scale-050-medium-emphasis': colorsTuple(
      themeVars['color-on/2-scale/050/medium-emphasis']
    ),
    'color-on-2-scale-050-disabled': colorsTuple(themeVars['color-on/2-scale/050/disabled']),
    'color-on-success-default-high-emphasis': colorsTuple(
      themeVars['color-on/success/default/high-emphasis']
    ),
    'color-success-states-hover': colorsTuple(themeVars['color/success/states/hover']),
    'color-success-states-pressed': colorsTuple(themeVars['color/success/states/pressed']),
    'color-success-states-focused': colorsTuple(themeVars['color/success/states/focused']),
    'color-success-states-selected': colorsTuple(themeVars['color/success/states/selected']),
    'color-success-states-disabled': colorsTuple(themeVars['color/success/states/disabled']),
    'color-warning-states-hover': colorsTuple(themeVars['color/warning/states/hover']),
    'color-warning-states-pressed': colorsTuple(themeVars['color/warning/states/pressed']),
    'color-warning-states-focused': colorsTuple(themeVars['color/warning/states/focused']),
    'color-warning-states-selected': colorsTuple(themeVars['color/warning/states/selected']),
    'color-warning-states-disabled': colorsTuple(themeVars['color/warning/states/disabled']),
    'color-on-success-default-medium-emphasis': colorsTuple(
      themeVars['color-on/success/default/medium-emphasis']
    ),
    'color-on-success-default-disabled': colorsTuple(
      themeVars['color-on/success/default/disabled']
    ),
    'color-on-success-default-action-text-default': colorsTuple(
      themeVars['color-on/success/default/action-text-default']
    ),
    'color-on-success-default-action-text-hover': colorsTuple(
      themeVars['color-on/success/default/action-text-hover']
    ),
    'color-on-success-default-action-text-pressed': colorsTuple(
      themeVars['color-on/success/default/action-text-pressed']
    ),
    'color-on-success-default-action-text-focused': colorsTuple(
      themeVars['color-on/success/default/action-text-focused']
    ),
    'color-on-success-default-action-text-selected': colorsTuple(
      themeVars['color-on/success/default/action-text-selected']
    ),
    'color-on-success-default-action-text-disabled': colorsTuple(
      themeVars['color-on/success/default/action-text-disabled']
    ),
    'color-on-warning-default-high-emphasis': colorsTuple(
      themeVars['color-on/warning/default/high-emphasis']
    ),
    'color-on-warning-default-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/default/medium-emphasis']
    ),
    'color-on-warning-default-disabled': colorsTuple(
      themeVars['color-on/warning/default/disabled']
    ),
    'color-on-warning-default-action-text-default': colorsTuple(
      themeVars['color-on/warning/default/action-text-default']
    ),
    'color-on-warning-default-action-text-hover': colorsTuple(
      themeVars['color-on/warning/default/action-text-hover']
    ),
    'color-on-warning-default-action-text-pressed': colorsTuple(
      themeVars['color-on/warning/default/action-text-pressed']
    ),
    'color-on-warning-default-action-text-focused': colorsTuple(
      themeVars['color-on/warning/default/action-text-focused']
    ),
    'color-on-warning-default-action-text-selected': colorsTuple(
      themeVars['color-on/warning/default/action-text-selected']
    ),
    'color-on-warning-default-action-text-disabled': colorsTuple(
      themeVars['color-on/warning/default/action-text-disabled']
    ),
    'color-on-success-900-high-emphasis': colorsTuple(
      themeVars['color-on/success/900/high-emphasis']
    ),
    'color-on-success-900-medium-emphasis': colorsTuple(
      themeVars['color-on/success/900/medium-emphasis']
    ),
    'color-on-success-900-disabled': colorsTuple(themeVars['color-on/success/900/disabled']),
    'color-on-surface-high-emphasis': colorsTuple(themeVars['color-on/surface/high-emphasis']),
    'color-on-surface-medium-emphasis': colorsTuple(themeVars['color-on/surface/medium-emphasis']),
    'color-on-surface-disabled': colorsTuple(themeVars['color-on/surface/disabled']),
    'color-on-surface-alert': colorsTuple(themeVars['color-on/surface/alert']),
    'color-on-surface-success': colorsTuple(themeVars['color-on/surface/success']),
    'color-on-surface-action-text-default': colorsTuple(
      themeVars['color-on/surface/action-text-default']
    ),
    'color-on-surface-action-text-hover': colorsTuple(
      themeVars['color-on/surface/action-text-hover']
    ),
    'color-on-surface-action-text-pressed': colorsTuple(
      themeVars['color-on/surface/action-text-pressed']
    ),
    'color-on-surface-action-text-focused': colorsTuple(
      themeVars['color-on/surface/action-text-focused']
    ),
    'color-on-surface-action-text-selected': colorsTuple(
      themeVars['color-on/surface/action-text-selected']
    ),
    'color-on-surface-action-text-disabled': colorsTuple(
      themeVars['color-on/surface/action-text-disabled']
    ),
    'color-on-alert-800-high-emphasis': colorsTuple(themeVars['color-on/alert/800/high-emphasis']),
    'color-on-alert-800-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/800/medium-emphasis']
    ),
    'color-on-alert-800-disabled': colorsTuple(themeVars['color-on/alert/800/disabled']),
    'color-on-alert-700-high-emphasis': colorsTuple(themeVars['color-on/alert/700/high-emphasis']),
    'color-on-alert-700-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/700/medium-emphasis']
    ),
    'color-on-alert-700-disabled': colorsTuple(themeVars['color-on/alert/700/disabled']),
    'color-on-alert-600-high-emphasis': colorsTuple(themeVars['color-on/alert/600/high-emphasis']),
    'color-on-alert-600-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/600/medium-emphasis']
    ),
    'color-on-alert-600-disabled': colorsTuple(themeVars['color-on/alert/600/disabled']),
    'color-on-alert-500-high-emphasis': colorsTuple(themeVars['color-on/alert/500/high-emphasis']),
    'color-on-alert-500-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/500/medium-emphasis']
    ),
    'color-on-alert-500-disabled': colorsTuple(themeVars['color-on/alert/500/disabled']),
    'color-on-alert-400-high-emphasis': colorsTuple(themeVars['color-on/alert/400/high-emphasis']),
    'color-on-alert-400-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/400/medium-emphasis']
    ),
    'color-on-alert-400-disabled': colorsTuple(themeVars['color-on/alert/400/disabled']),
    'color-on-alert-300-high-emphasis': colorsTuple(themeVars['color-on/alert/300/high-emphasis']),
    'color-on-alert-300-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/300/medium-emphasis']
    ),
    'color-on-alert-300-disabled': colorsTuple(themeVars['color-on/alert/300/disabled']),
    'color-on-alert-200-high-emphasis': colorsTuple(themeVars['color-on/alert/200/high-emphasis']),
    'color-on-alert-200-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/200/medium-emphasis']
    ),
    'color-on-alert-200-disabled': colorsTuple(themeVars['color-on/alert/200/disabled']),
    'color-on-alert-100-high-emphasis': colorsTuple(themeVars['color-on/alert/100/high-emphasis']),
    'color-on-alert-100-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/100/medium-emphasis']
    ),
    'color-on-alert-100-disabled': colorsTuple(themeVars['color-on/alert/100/disabled']),
    'color-on-alert-050-high-emphasis': colorsTuple(themeVars['color-on/alert/050/high-emphasis']),
    'color-on-alert-050-medium-emphasis': colorsTuple(
      themeVars['color-on/alert/050/medium-emphasis']
    ),
    'color-on-alert-050-disabled': colorsTuple(themeVars['color-on/alert/050/disabled']),
    'color-on-success-800-high-emphasis': colorsTuple(
      themeVars['color-on/success/800/high-emphasis']
    ),
    'color-on-success-800-medium-emphasis': colorsTuple(
      themeVars['color-on/success/800/medium-emphasis']
    ),
    'color-on-success-800-disabled': colorsTuple(themeVars['color-on/success/800/disabled']),
    'color-on-success-700-high-emphasis': colorsTuple(
      themeVars['color-on/success/700/high-emphasis']
    ),
    'color-on-success-700-medium-emphasis': colorsTuple(
      themeVars['color-on/success/700/medium-emphasis']
    ),
    'color-on-success-700-disabled': colorsTuple(themeVars['color-on/success/700/disabled']),
    'color-on-success-600-high-emphasis': colorsTuple(
      themeVars['color-on/success/600/high-emphasis']
    ),
    'color-on-success-600-medium-emphasis': colorsTuple(
      themeVars['color-on/success/600/medium-emphasis']
    ),
    'color-on-success-600-disabled': colorsTuple(themeVars['color-on/success/600/disabled']),
    'color-on-success-500-high-emphasis': colorsTuple(
      themeVars['color-on/success/500/high-emphasis']
    ),
    'color-on-success-500-medium-emphasis': colorsTuple(
      themeVars['color-on/success/500/medium-emphasis']
    ),
    'color-on-success-500-disabled': colorsTuple(themeVars['color-on/success/500/disabled']),
    'color-on-success-400-high-emphasis': colorsTuple(
      themeVars['color-on/success/400/high-emphasis']
    ),
    'color-on-success-400-medium-emphasis': colorsTuple(
      themeVars['color-on/success/400/medium-emphasis']
    ),
    'color-on-success-400-disabled': colorsTuple(themeVars['color-on/success/400/disabled']),
    'color-on-success-300-high-emphasis': colorsTuple(
      themeVars['color-on/success/300/high-emphasis']
    ),
    'color-on-success-300-medium-emphasis': colorsTuple(
      themeVars['color-on/success/300/medium-emphasis']
    ),
    'color-on-success-300-disabled': colorsTuple(themeVars['color-on/success/300/disabled']),
    'color-on-success-200-high-emphasis': colorsTuple(
      themeVars['color-on/success/200/high-emphasis']
    ),
    'color-on-success-200-medium-emphasis': colorsTuple(
      themeVars['color-on/success/200/medium-emphasis']
    ),
    'color-on-success-200-disabled': colorsTuple(themeVars['color-on/success/200/disabled']),
    'color-on-success-100-high-emphasis': colorsTuple(
      themeVars['color-on/success/100/high-emphasis']
    ),
    'color-on-success-100-medium-emphasis': colorsTuple(
      themeVars['color-on/success/100/medium-emphasis']
    ),
    'color-on-success-100-disabled': colorsTuple(themeVars['color-on/success/100/disabled']),
    'color-on-success-050-high-emphasis': colorsTuple(
      themeVars['color-on/success/050/high-emphasis']
    ),
    'color-on-success-050-medium-emphasis': colorsTuple(
      themeVars['color-on/success/050/medium-emphasis']
    ),
    'color-on-success-050-disabled': colorsTuple(themeVars['color-on/success/050/disabled']),
    'color-warning-default': colorsTuple(themeVars['color/warning/default']),
    'color-warning-900': colorsTuple(themeVars['color/warning/900']),
    'color-warning-800': colorsTuple(themeVars['color/warning/800']),
    'color-warning-700': colorsTuple(themeVars['color/warning/700']),
    'color-warning-600': colorsTuple(themeVars['color/warning/600']),
    'color-warning-500': colorsTuple(themeVars['color/warning/500']),
    'color-warning-400': colorsTuple(themeVars['color/warning/400']),
    'color-warning-300': colorsTuple(themeVars['color/warning/300']),
    'color-warning-200': colorsTuple(themeVars['color/warning/200']),
    'color-warning-100': colorsTuple(themeVars['color/warning/100']),
    'color-warning-50': colorsTuple(themeVars['color/warning/50']),
    'color-on-warning-900-high-emphasis': colorsTuple(
      themeVars['color-on/warning/900/high-emphasis']
    ),
    'color-on-warning-900-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/900/medium-emphasis']
    ),
    'color-on-warning-900-disabled': colorsTuple(themeVars['color-on/warning/900/disabled']),
    'color-on-warning-800-high-emphasis': colorsTuple(
      themeVars['color-on/warning/800/high-emphasis']
    ),
    'color-on-warning-800-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/800/medium-emphasis']
    ),
    'color-on-warning-800-disabled': colorsTuple(themeVars['color-on/warning/800/disabled']),
    'color-on-warning-700-high-emphasis': colorsTuple(
      themeVars['color-on/warning/700/high-emphasis']
    ),
    'color-on-warning-700-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/700/medium-emphasis']
    ),
    'color-on-warning-700-disabled': colorsTuple(themeVars['color-on/warning/700/disabled']),
    'color-on-warning-600-high-emphasis': colorsTuple(
      themeVars['color-on/warning/600/high-emphasis']
    ),
    'color-on-warning-600-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/600/medium-emphasis']
    ),
    'color-on-warning-600-disabled': colorsTuple(themeVars['color-on/warning/600/disabled']),
    'color-on-warning-500-high-emphasis': colorsTuple(
      themeVars['color-on/warning/500/high-emphasis']
    ),
    'color-on-warning-500-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/500/medium-emphasis']
    ),
    'color-on-warning-500-disabled': colorsTuple(themeVars['color-on/warning/500/disabled']),
    'color-on-warning-400-high-emphasis': colorsTuple(
      themeVars['color-on/warning/400/high-emphasis']
    ),
    'color-on-warning-400-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/400/medium-emphasis']
    ),
    'color-on-warning-400-disabled': colorsTuple(themeVars['color-on/warning/400/disabled']),
    'color-on-warning-300-high-emphasis': colorsTuple(
      themeVars['color-on/warning/300/high-emphasis']
    ),
    'color-on-warning-300-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/300/medium-emphasis']
    ),
    'color-on-warning-300-disabled': colorsTuple(themeVars['color-on/warning/300/disabled']),
    'color-on-warning-200-high-emphasis': colorsTuple(
      themeVars['color-on/warning/200/high-emphasis']
    ),
    'color-on-warning-200-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/200/medium-emphasis']
    ),
    'color-on-warning-200-disabled': colorsTuple(themeVars['color-on/warning/200/disabled']),
    'color-on-warning-100-high-emphasis': colorsTuple(
      themeVars['color-on/warning/100/high-emphasis']
    ),
    'color-on-warning-100-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/100/medium-emphasis']
    ),
    'color-on-warning-100-disabled': colorsTuple(themeVars['color-on/warning/100/disabled']),
    'color-on-warning-050-high-emphasis': colorsTuple(
      themeVars['color-on/warning/050/high-emphasis']
    ),
    'color-on-warning-050-medium-emphasis': colorsTuple(
      themeVars['color-on/warning/050/medium-emphasis']
    ),
    'color-on-warning-050-disabled': colorsTuple(themeVars['color-on/warning/050/disabled']),
  },
  radius: {
    'size-border-radius-0-5x': '16px',
    'size-border-radius-default': '32px',
    'size-border-radius-1-5x': '48px',
    'size-border-radius-2x': '64px',
    'size-border-radius-3x': '96px',
    'size-border-radius-4x': '128px',
  },
  fontSizes: {},
});
