/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { RecursicarecursicaTokens } from './RecursicarecursicaTokens';
import { themeVars } from './RecursicarecursicaContractTheme.css';
import { uiKit } from './RecursicarecursicaUiKit';

export const recursica = {
  ...uiKit,
  ...themeVars,
  ...RecursicarecursicaTokens,
}
