/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

export const AvailableThemes = ["DefaultMode1Theme", "DefaultLightTheme", "DefaultDarkTheme"] as const;
export type AvailableThemesType = (typeof AvailableThemes)[number];
