export function autoGeneratedFile() {
  return `/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly\n
For more information about Recursica, go to https://recursica.com
*/
`;
}
