import { autoGeneratedFile } from '../utils/autoGeneratedFile';

export function generateColorsType(colorTokens: string[], outputPath: string) {
  const colorsType = `${autoGeneratedFile()}
export type RecursicaColors = \n\t"${colorTokens.join('" |\n\t"')}";\n`;
  return {
    content: colorsType,
    path: `${outputPath}/RecursicaColorsType.ts`,
    filename: 'RecursicaColorsType.ts',
  };
}
