import { autoGeneratedFile } from '../utils/autoGeneratedFile';
import path from 'path';

export function createRecursicaObject(project: string, outputPath: string) {
  const tokens = `Recursica${project}Tokens`;
  const contract = `Recursica${project}ContractTheme`;
  const uiKit = `Recursica${project}UiKit`;

  const recursicaObjectContent = `${autoGeneratedFile()}
import { ${tokens} } from './${tokens}';
import { themeVars } from './${contract}.css';
import { uiKit } from './${uiKit}';

export const recursica = {
  ...uiKit,
  ...themeVars,
  ...${tokens},
}
`;
  return {
    content: recursicaObjectContent,
    path: path.join(outputPath, 'Recursica.ts'),
    filename: 'Recursica.ts',
  };
}
