import { autoGeneratedFile } from '../utils/autoGeneratedFile';
import fs from 'fs';
import path from 'path';

export function createRecursicaObject(project: string, outputPath: string) {
  const tokens = `Recursica${project}Tokens`;
  const contract = `Recursica${project}ContractTheme`;
  const uiKit = `Recursica${project}UiKit`;

  const recursicaObjectContent = `${autoGeneratedFile()}
import { ${tokens} } from './${tokens}';
import { themeVars } from './${contract}.css';
import { uiKit } from './${uiKit}';

export const recursica = {
  ...uiKit,
  ...themeVars,
  ...${tokens},
}
`;
  fs.writeFileSync(path.join(outputPath, 'Recursica.ts'), recursicaObjectContent);

  return 'Recursica.ts';
}
